# Generated by Django 5.0.2 on 2024-03-06 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('size', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('amount_of_dies_hit_points', models.IntegerField()),
                ('amount_of_dies_strength', models.IntegerField()),
                ('amount_of_dies_speed', models.IntegerField()),
                ('amount_of_dies_mana', models.IntegerField()),
                ('added_value_hit_points', models.IntegerField()),
                ('added_value_strength', models.IntegerField()),
                ('added_value_speed', models.IntegerField()),
                ('added_value_mana', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('gold', models.IntegerField(default=1500)),
                ('division', models.IntegerField(default=4)),
                ('points', models.IntegerField(default=0)),
                ('is_in_cup', models.BooleanField(default=True)),
                ('last_season_placement', models.PositiveIntegerField(null=True)),
                ('championship_wins', models.IntegerField(default=0)),
                ('cup_wins', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gladiator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('salary', models.IntegerField(null=True)),
                ('wounded_months', models.IntegerField(default=0)),
                ('age', models.IntegerField(null=True)),
                ('knockouts_season', models.IntegerField(default=0)),
                ('knockouts_total', models.IntegerField(default=0)),
                ('has_movement_left', models.BooleanField(default=True)),
                ('max_hit_points', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('mana', models.IntegerField(default=0)),
                ('spear_hit', models.IntegerField(default=0)),
                ('sword_hit', models.IntegerField(default=0)),
                ('axe_hit', models.IntegerField(default=0)),
                ('club_hit', models.IntegerField(default=0)),
                ('spear_parry', models.IntegerField(default=0)),
                ('sword_parry', models.IntegerField(default=0)),
                ('axe_parry', models.IntegerField(default=0)),
                ('club_parry', models.IntegerField(default=0)),
                ('fist_hit', models.IntegerField(default=0)),
                ('bow_hit', models.IntegerField(default=0)),
                ('crossbow_hit', models.IntegerField(default=0)),
                ('evade', models.IntegerField(default=0)),
                ('resist_spell', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.race')),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.team')),
            ],
        ),
    ]
