# Generated by Django 5.0.2 on 2024-03-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gladiator',
            name='spells',
            field=models.IntegerField(default=0),
        ),
    ]
