# Generated by Django 5.0.2 on 2024-03-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gladiator_spells'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gladiator',
            name='spells',
        ),
    ]
