# Generated by Django 5.0.2 on 2024-03-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_gladiator_spells'),
    ]

    operations = [
        migrations.AddField(
            model_name='gladiator',
            name='melee_damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gladiator',
            name='spell_skill',
            field=models.IntegerField(default=0),
        ),
    ]
